import { NodeTypeDefinition } from '@/types/canvas';

export const NODE_TYPES: NodeTypeDefinition[] = [
  {
    type: 'manualTrigger',
    label: 'Manual Trigger',
    labelHe: 'הפעלה ידנית',
    labelEn: 'Manual Trigger',
    category: 'trigger',
    icon: 'Play',
    color: '#FF6D5A',
    bgColor: '#2A1A17',
    configFields: [],
    defaultData: { label: 'Manual Trigger' },
  },
  {
    type: 'httpRequest',
    label: 'HTTP Request',
    labelHe: 'בקשת HTTP',
    labelEn: 'HTTP Request',
    category: 'core',
    icon: 'Globe',
    color: '#00D4FF',
    bgColor: '#0F1F2A',
    configFields: [
      { key: 'url', label: 'URL', type: 'string', default: 'https://api.example.com' },
      { key: 'method', label: 'Method', type: 'string', default: 'GET' },
    ],
    defaultData: { label: 'HTTP Request', url: 'https://api.example.com', method: 'GET' },
  },
  {
    type: 'set',
    label: 'Set',
    labelHe: 'Set',
    labelEn: 'Set',
    category: 'core',
    icon: 'Edit',
    color: '#00D4FF',
    bgColor: '#0F1F2A',
    configFields: [
      { key: 'value', label: 'Value', type: 'string', default: '' },
      { key: 'mode', label: 'Mode', type: 'string', default: 'merge' },
    ],
    defaultData: { label: 'Set', value: '', mode: 'merge' },
  },
  {
    type: 'if',
    label: 'IF',
    labelHe: 'IF',
    labelEn: 'IF',
    category: 'core',
    icon: 'GitBranch',
    color: '#00D4FF',
    bgColor: '#0F1F2A',
    configFields: [
      { key: 'condition', label: 'Condition', type: 'string', default: '$json.value > 10' },
    ],
    defaultData: { label: 'IF', condition: '$json.value > 10' },
  },
  {
    type: 'switch',
    label: 'Switch',
    labelHe: 'Switch',
    labelEn: 'Switch',
    category: 'core',
    icon: 'GitBranch',
    color: '#00D4FF',
    bgColor: '#0F1F2A',
    configFields: [
      { key: 'rules', label: 'Rules', type: 'json', default: [] },
    ],
    defaultData: { label: 'Switch', rules: [] },
  },
  {
    type: 'code',
    label: 'Code',
    labelHe: 'קוד',
    labelEn: 'Code',
    category: 'core',
    icon: 'Code',
    color: '#00D4FF',
    bgColor: '#0F1F2A',
    configFields: [
      { key: 'code', label: 'JavaScript', type: 'string', default: 'return [$input.all()];' },
    ],
    defaultData: { label: 'Code', code: 'return [$input.all()];' },
  },
  {
    type: 'function',
    label: 'Function',
    labelHe: 'Function',
    labelEn: 'Function',
    category: 'core',
    icon: 'Braces',
    color: '#00D4FF',
    bgColor: '#0F1F2A',
    configFields: [
      { key: 'functionCode', label: 'Function', type: 'string', default: 'return items;' },
    ],
    defaultData: { label: 'Function', functionCode: 'return items;' },
  },
  {
    type: 'merge',
    label: 'Merge',
    labelHe: 'Merge',
    labelEn: 'Merge',
    category: 'core',
    icon: 'Merge',
    color: '#00D4FF',
    bgColor: '#0F1F2A',
    configFields: [{ key: 'mode', label: 'Mode', type: 'string', default: 'append' }],
    defaultData: { label: 'Merge', mode: 'append' },
  },
  {
    type: 'splitInBatches',
    label: 'Split In Batches',
    labelHe: 'Split In Batches',
    labelEn: 'Split In Batches',
    category: 'core',
    icon: 'Layers',
    color: '#00D4FF',
    bgColor: '#0F1F2A',
    configFields: [{ key: 'batchSize', label: 'Batch Size', type: 'number', default: 10 }],
    defaultData: { label: 'Split In Batches', batchSize: 10 },
  },
  {
    type: 'wait',
    label: 'Wait',
    labelHe: 'המתנה',
    labelEn: 'Wait',
    category: 'core',
    icon: 'Clock',
    color: '#00D4FF',
    bgColor: '#0F1F2A',
    configFields: [{ key: 'amount', label: 'Seconds', type: 'number', default: 1 }],
    defaultData: { label: 'Wait', amount: 1 },
  },
  {
    type: 'gmail',
    label: 'Gmail',
    labelHe: 'Gmail',
    labelEn: 'Gmail',
    category: 'integration',
    icon: 'Mail',
    color: '#A855F7',
    bgColor: '#1A0F2A',
    configFields: [
      { key: 'operation', label: 'Operation', type: 'string', default: 'send' },
      { key: 'to', label: 'To', type: 'string', default: '' },
      { key: 'subject', label: 'Subject', type: 'string', default: '' },
      { key: 'message', label: 'Message', type: 'string', default: '' },
    ],
    defaultData: { label: 'Gmail', operation: 'send', to: '', subject: '', message: '' },
  },
  {
    type: 'slack',
    label: 'Slack',
    labelHe: 'Slack',
    labelEn: 'Slack',
    category: 'integration',
    icon: 'MessageCircle',
    color: '#A855F7',
    bgColor: '#1A0F2A',
    configFields: [
      { key: 'channel', label: 'Channel', type: 'string', default: '' },
      { key: 'text', label: 'Text', type: 'string', default: '' },
    ],
    defaultData: { label: 'Slack', channel: '', text: '' },
  },
  {
    type: 'googleSheets',
    label: 'Google Sheets',
    labelHe: 'Google Sheets',
    labelEn: 'Google Sheets',
    category: 'integration',
    icon: 'Table',
    color: '#A855F7',
    bgColor: '#1A0F2A',
    configFields: [
      { key: 'operation', label: 'Operation', type: 'string', default: 'read' },
      { key: 'sheetId', label: 'Sheet ID', type: 'string', default: '' },
    ],
    defaultData: { label: 'Google Sheets', operation: 'read', sheetId: '' },
  },
  {
    type: 'notion',
    label: 'Notion',
    labelHe: 'Notion',
    labelEn: 'Notion',
    category: 'integration',
    icon: 'FileText',
    color: '#A855F7',
    bgColor: '#1A0F2A',
    configFields: [
      { key: 'operation', label: 'Operation', type: 'string', default: 'create' },
      { key: 'databaseId', label: 'Database ID', type: 'string', default: '' },
    ],
    defaultData: { label: 'Notion', operation: 'create', databaseId: '' },
  },
  {
    type: 'openAI',
    label: 'OpenAI',
    labelHe: 'OpenAI',
    labelEn: 'OpenAI',
    category: 'ai',
    icon: 'Bot',
    color: '#00FF94',
    bgColor: '#0F2A1A',
    configFields: [
      { key: 'model', label: 'Model', type: 'string', default: 'gpt-3.5-turbo' },
      { key: 'prompt', label: 'Prompt', type: 'string', default: '' },
    ],
    defaultData: { label: 'OpenAI', model: 'gpt-3.5-turbo', prompt: '' },
  },
];

export const NODE_TYPE_MAP = new Map(NODE_TYPES.map((n) => [n.type, n]));

export function getNodeDefinition(type: string): NodeTypeDefinition | undefined {
  return NODE_TYPE_MAP.get(type);
}
